### ISSUE TITLE
Travel Checklist

### ISSUE THREAD

**Issue by Danielschuetzle** [Danielschuetzle/Wayfarer-App#14]
## User Story: Travel Checklist

As a travel enthusiast, 
I want to create and manage a checklist of activities 
so that I can ensure I remember all the items I need to pack and tasks I need to complete before my trip.

### Description

Users can create a new checklist for each trip they're planning, adding tasks or items they need to remember. Each task can be marked as completed directly from the checklist. Completed tasks are visually distinct from pending tasks, providing an overview of the remaining preparations. 

### Acceptance Criteria
- [ ] Users can create a new checklist for each trip.
- [ ] Users can add items to their checklist.
- [ ] Users can mark items as completed.
- [ ] Completed and pending tasks are visually distinct.

### Tasks
- [ ] Implement functionality to create a new checklist for each trip.
- [ ] Develop UI to add tasks or items to the checklist.
- [ ] Add feature to mark tasks or items as completed.
- [ ] Distinguish visually between completed and pending tasks.

**Comment by JonasDaJones** [comment]
As far as I understand, the activities are set up in the form, but edited (checked) on the overview list (on the img), correct? In this case, this US works fine. cheers
