### ISSUE TITLE
Image Uploads

### ISSUE THREAD

**Issue by Danielschuetzle** [Danielschuetzle/Wayfarer-App#15]
## User Story: Image Uploads

As a travel enthusiast,
I want to attach images to my travel plans,
so that I can have visual reminders and references associated with each destination and keep important travel documents handy.

### Description

Users can add images to their travel plans during the creation or editing process. This can be photos of the destination, images of important documents like passports, visas, or tickets, or any other relevant visual reference. Users can upload images from their device or from cloud storage. Each travel plan can include multiple images, all displayed in a user-friendly gallery view.

### Acceptance Criteria
- [ ] Users can upload images during the creation or editing of their travel plans.
- [ ] Users can upload images from their device.
- [ ] Images are displayed in a gallery view within the travel plan.

### Tasks
- [ ] Implement functionality to upload images during the creation or editing of travel plans.
- [ ] Implement a  gallery view for displaying images.

**Comment by MariaRiosNavarro** [comment]
Another good US, again clean and clear, I just think your Value Proposition it's a bit long, especially the last sentence, but it's a matter of taste. I don't know how you could shorten it either 😅
