### ISSUE TITLE
Trip Budgeting Feature

### ISSUE THREAD

**Issue by Danielschuetzle** [Danielschuetzle/Wayfarer-App#16]
# Trip Budgeting

As a traveler,
I want to assign a budget to each of my travel plans,
so that I can manage my finances and prevent overspending.

### Description

users are able to assign a single budget amount to each of their travel plans. The user can enter their intended budget when creating or editing their travel plans. The budget will be displayed along with other travel plan details.

### Acceptance Criteria
- [ ] Users can assign a budget to their travel plans while creating or editing them.
- [ ] The assigned budget is displayed in the travel plan details.

### Tasks
- [ ] Add a budget input field in the Travelplanform.
- [ ] Display the assigned budget in the travel plan details view.

**Comment by dimitriosxmi** [comment]
LGTM ⭐ 
The US's goal is quite understandable to me and very nicely described!
