### ISSUE TITLE
Calendar Timeline View

### ISSUE THREAD

**Issue by Danielschuetzle** [Danielschuetzle/Wayfarer-App#7]
# View Travel Plans on a Calendar Timeline View

As a traveler, 
I want to view my travel plans on a calendar or timeline view 
so that I can have a visual representation of my trip schedule.

## Description

Users can navigate to a calendar or timeline view that displays their travel plans in a graphical format. Each travel plan will be represented as an event on the calendar or timeline, showing the dates,, and destinations. This view provides a visual representation of the trip schedule, allowing users to easily see the duration and timing of their plans.

<img width="381" alt="Bildschirmfoto 2023-06-22 um 14 28 18" src="https://github.com/Danielschuetzle/Wayfarer-App/assets/102250825/cdbf6fde-bd96-4bbc-acb3-ced577e61ae1">

![Bildschirmfoto 2023-06-22 um 11 40 56](https://github.com/Danielschuetzle/Wayfarer-App/assets/102250825/157038c2-f85f-4ef9-b92d-c844a67813d6)

## Acceptance Criteria

 - [ ] Users can see a calendar view from their dashboard
 - [ ] The calendar or timeline view displays travel plans as events or items.
 - [ ] Each travel plan event or item shows the dates and is highlighted in the calendar.

## Tasks
  - [ ] Implement a calendar component to display the travel plans.
  - [ ] Implement a calendar on the dashboard. 
  - [ ] Retrieve the travel plans from the localstorage and render them in the calendar view.
  - [ ] Ensure the calendar or timeline view accurately represents the duration and timing of the travel plans.

**Comment by FelineHuhn** [comment]
Hey Daniel, good work and I think this feature is great! 🎉

I have one question: How does the user get to the timeline view? Maybe you could create a second wireframe where you can see from where and how the user navigates to the timeline view? And also this should be mentioned in the acceptance criteria and tasks, or?

**Comment by mbosselmann** [comment]
Hi Daniel,
LGTM! :octocat:
